special_signs = {
    "1":" one ",
    "!":" exclamation mark ",
    "2":" two ",
    "@":" at ",
    "3":" three ",
    "#":" hashtag ",
    "4":" four ",
    "$":" dollar sign ",
    "5":" five ",
    "%":" percentage ",
    "6":" six ",
    "^":" circumflex ",
    "7":" seven ",
    "&":" ampersand ",
    "8":" eight ",
    "*":" asteriks ",
    "(":" left parenthesis ",
    ")":" right parenthesis ",
    "-":" minus ",
    "_":" underscore ",
    "+":" plus ", 
    "=":" equal ",
    "~":" tilde ",
    "<":" less then ",
    ">":" greater then ",
    ",":" comma ",
    "?":" question mark ",
    "/":" slash ",
    "\\":" backslash ",
    "\'":" apostrophe ",
    "\"":" quotation mark ",
    "≈":" almost equal to ",
    "`":" backtick ",
    "‱":" basis point ",
    "[":" square bracket opens ",
    "]":" square bracket closes ",
    "•":" bullet-point ",
    ":":" colon ",
    ";":" semi-colon ",
    "©":" copy-right ",
    "—":" dash ",
    "°":" degree ",
    "÷":" division ",
    "℮":" estimated sign ",
    "»":" quote closed ",
    "«":" quote opened ",
    "¡":" inverted exclamation mark ",
    "¿":" inverted question mark ",
    "×":" multiplication ",
    "№":" numero ",
    "|":" vertical bar sign ",
    "±":" plus minus ",
    "§":" section sign ",
    "\n":""
}